In [1]:
import numpy as np

#### Numpy is built in linear algebra, distributions, trigonometric and random probabilities formula.

In [2]:
mylist = [1,2,3]
type(mylist)

list

In [4]:
#transform to numpy array
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

#### sample methods

In [11]:
np.arange(0,101,20) # create range with step size

array([  0,  20,  40,  60,  80, 100])

In [15]:
# first property is row, second property 
# is column for two dimensional datasets
np.zeros((2,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
#getting linearly spaced between the numbers
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])