In [1]:
import numpy as np

#### Numpy is built in linear algebra, distributions, trigonometric and random probabilities formula.

In [2]:
mylist = [1,2,3]
type(mylist)

list

In [4]:
#transform to numpy array
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

#### sample methods

In [11]:
np.arange(0,101,20) # create range with step size

array([  0,  20,  40,  60,  80, 100])

In [15]:
# first property is row, second property 
# is column for two dimensional datasets
np.zeros((2,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
#getting linearly spaced between the numbers
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
#create same number of columns with the same number of rows
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
#random number between 0 and 1
np.random.rand(1)

array([0.19701372])

In [29]:
#return numbers from standard normal distribution
np.random.randn(2,3)

array([[-1.35706589, -1.06993763, -0.38488726],
       [ 0.1607403 , -0.18363762, -0.98522821]])

In [31]:
#returns random integers
np.random.randint(0, 101, 5)

array([54, 27, 74,  6, 72])

In [33]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [36]:
##reshaping two dimensional arrays 
arr = np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr = np.random.randint(0,101,10)

In [39]:
# get max value
ranarr.max()

92

In [40]:
# get min value
ranarr.min()

4

In [41]:
#get index location of maximum number
ranarr.argmax()

7

In [44]:
#get index location of minimum number
ranarr.argmin()

3

In [46]:
#check datatype of array
ranarr.dtype

dtype('int64')

In [47]:
#get shape of array
arr.shape

(25,)

In [49]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
arr.shape

(5, 5)